Repository ad-earth/client-v2.0, pull requests merged in 2023-04, with the labels that each got.

#43 refac. react-query custom hook 관심사 분리 #29
  src/pages/CompletePage.tsx
  src/query/useComplete.ts
  src/query/usePayment.ts
Labels: refactoring

#48 Refac/dam
  src/components/cart/CartItem.tsx
  src/components/cart/CartOptionModal.tsx
  src/components/common/Address.tsx
  src/components/common/UserInfoModal.tsx
  src/components/login/LoginSearchId.tsx
  src/components/login/LoginSearchPwd.tsx
  src/components/login/LoginSetNewPwd.tsx
  src/components/payment/PaymentAddDefault.tsx
  src/components/payment/PaymentInput.tsx
  src/pages/CartPage.tsx
  src/pages/CompletePage.tsx
  src/pages/LogInPage.tsx
  src/pages/PaymentPage.tsx
  src/pages/SignUpPage.tsx
  src/query/useAuth.ts
  src/query/useAuthSearch.ts
  src/query/useCart.ts
  src/query/usePayment.ts
  src/query/useUser.ts
  src/style/footer.style.ts
  src/style/header.style.ts
Labels: refactoring

#51 Refac/sol
  src/components/detail/DetailInfo.tsx
  src/elements/Heart.tsx
  src/query/useDeleteReview.ts
  src/query/useGetAdListQuery.ts
  src/query/useGetReviewsQuery.ts
  src/query/useProduct.ts
Labels: refactoring

#53 Refac/sol
  src/components/cart/CartOptionModal.tsx
  src/components/common/OptionBox.tsx
  src/components/common/SingleBox.tsx
  src/pages/DetailPage.tsx
  src/pages/ProtectedRoute.tsx
  src/query/useDetail.ts
  src/query/useProduct.ts
  src/shared/utils/RouteList.tsx
  src/shared/utils/Router.tsx
  src/style/box.style.ts
Labels: refactoring

#54 Refac/suin
  src/pages/MyWishPage.tsx
  src/query/usePostLikeQuery.ts
  src/query/useProduct.ts
  src/query/useReview.ts
  src/query/useWish.ts
  yarn.lock
Labels: refactoring

#63 fix. 회원가입 버튼 disable 조건 수정 & 프로필 이미지 요청 수정
  src/components/common/Profile.tsx
  src/elements/ProfileImage.tsx
  src/pages/SignUpPage.tsx
Labels: debug

#65 Fix/dam
  src/components/SearchBar.tsx
Labels: debug

#68 fix. 회원가입시 로그인페이지로 라우팅 수정
  src/query/useAuth.ts
Labels: debug

#69 fix. 쿼리키 누락 수정
  src/components/common/OptionBox.tsx
  src/components/detail/DetailModal.tsx
  src/query/useProduct.ts
  src/redux/reducer/qtySlice.ts
  src/redux/store.ts
Labels: debug

#70 fix. 회원탈퇴 후 헤더 변경 버그 수정
  src/query/useUser.ts
Labels: debug

#72 fix. 검색 결과 개수 누락 수정
  src/pages/SearchPage.tsx
Labels: debug

#74 feat. page를 state에서 쿼리스트링으로 처리
  src/components/SearchBar.tsx
  src/components/common/Card.tsx
  src/components/detail/DetailContents.tsx
  src/components/detail/DetailReviews.tsx
  src/components/list/ListCategory.tsx
  src/components/search/SearchCards.tsx
  src/constants/index.ts
  src/elements/Pagination.tsx
  src/pages/DetailPage.tsx
  src/pages/ListPage.tsx
  src/pages/SearchPage.tsx
  src/query/useReview.ts
  src/redux/reducer/pageSlice.ts
  src/redux/store.ts
Labels: enhancement

#75 Fix/sol
  src/components/common/OptionBox.tsx
  src/style/listCards.style.ts
Labels: debug

#76 fix. 사이즈 옵션 버그 수정
  src/components/common/OptionBox.tsx
  src/redux/reducer/optionSlice.ts
Labels: debug

#78 fix. ScrollRestoration 전체페이지 스크롤 반영 #77
  src/pages/DetailPage.tsx
  src/shared/utils/Router.tsx
Labels: debug

#79 fix. 로그인 아이디, 패스워드 입력시 공백제거
  src/constants/index.ts
  src/pages/LogInPage.tsx
Labels: debug

#80 fix. 상품 목록 새로고침 버그
  src/components/list/ListCategory.tsx
Labels: debug

#81 Fix/sol
  src/components/cart/CartItem.tsx
  src/components/my/MyOrderList.tsx
  src/shared/api/instance.ts
Labels: debug

#82 Fix/dam
  src/components/detail/DetailInfo.tsx
Labels: debug
